### PR TITLE
accept sce with no cells in some samples

### PR DESCRIPTION
**Pull request by lpantano**
Hi,

I ran into errors when the number of samples with cells in a giving cluster was 0. The creation of single cell experiment object will fail since not all assays are equally in dimension. 

I saw some commits to fix this, but when I was trying my data, that has 2-3 clusters where not all the 4 replicates for each group have cells, I get into errors. 

I modified the code to get it running, but I am not sure if you want to implement this or not. Feel free to ignore it, or implement in a different way, or anything else. 

I just thought to share it here.

Thanks!

### CODE REVIEW

**Comment by HelenaLC** [comment]
My understanding is that this is any issue with `pbMDS`, not `aggregateData` correct? If so, I have pushed a fix to the devel branch, package version 0.99.8. `pbMDS` now gives a message when, e.g., sample1-cluster4 don't contain any cells, removes it, and plots without failing.
Let me know if there's still issues remaining or, if this is what you meant, close the issue. Thanks for pointing this out!

**Comment by lpantano** [comment]
Thanks!

actually, I was having an issue with aggregate as well. I have 8 samples, but in some clusters I only have 6 or 7 since there are no cells for the remaining samples. At the step of creating the singlecell object, it gives me an error, since the dimension of the matrixes is different for different clusters (8,7 or 6). I'll try again with the last devel, and if I get the same error, I can share part of my data if you would like it to reproduce.

Thanks

**Comment by lpantano** [comment]
Thanks, I checked with the last version and it works. Not sure why I was getting the error for aggregateData, maybe I mixed branches.

Thank you, super useful!

**Comment by lpantano** [comment]
Hi,

sorry to bother again, but I found the error again, and I think last time I got my version of the package mixup with the remotes version.

If it is not a lot of trouble, could you tell me if this works for you? I am using a public data to try to reproduce this. I am removing all the cells from one `ind` and from one `cluster`. This gives me an error when creating the SingleCellExperiment Object inside aggregateData.

```
library(ExperimentHub)
eh <- ExperimentHub()
query(eh, "Kang")
sce <- eh[["EH2259"]]
sce <- sce[rowSums(counts(sce) > 0) > 0, ]
dim(sce)
sce = sce[,colData(sce)[["cluster"]] %in% c(5,9)] # use only two clusters
table(colData(sce)[["ind"]], colData(sce)[["cluster"]]) # prop inv vs clusters
sce = sce[,!(colData(sce)[["cluster"]]==5 & colData(sce)[["ind"]]==1488)] # remove all cells from one indv
table(colData(sce)[["ind"]], colData(sce)[["cluster"]]) # prop inv vs clusters

library(muscat)

pb_bal <- aggregateData(
    x = sce, assay = "counts", fun = "sum",
    by = c("cluster", "ind"))
```

Error:
`Error in method(object) : all assays must have the same nrow and ncol`

Thanks

## Session Info

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] muscat_0.99.7               scater_1.13.18              ggplot2_3.2.1              
 [4] muscData_0.99.6             SingleCellExperiment_1.7.7  SummarizedExperiment_1.15.8
 [7] DelayedArray_0.11.4         BiocParallel_1.19.2         matrixStats_0.54.0         
[10] Biobase_2.45.0              GenomicRanges_1.37.15       GenomeInfoDb_1.21.1        
[13] IRanges_2.19.14             S4Vectors_0.23.20           ExperimentHub_1.11.4       
[16] AnnotationHub_2.17.7        BiocFileCache_1.9.1         dbplyr_1.4.2               
[19] BiocGenerics_0.31.5        
```

**Comment by HelenaLC** [comment]
So; this was tricky. The reason I closed the issue earlier is because I couldn't reproduce it when removing a cluster-sample combination myself. I finally understood now why:
- the Kang SCE from `ExperimentHub` has the `ind` and `cell` columns as characters. This in turn results in `split` dropping any missing combinations.
- when using `prepSCE`, cluster, sample and group ID columns are assured to be factors; then `split` retrains missing combinations & I didn't get an error.
=> When using `prepSCE` prior to `aggregateData` this error disappears. But, I added a fix in `aggregateData` to assure the columns to aggregate by are factors, i.e., missing combinations will be retained regardless of whether `prepData` was run or not.

*Haven't pushed this yet as I'm trying to work on some other things before another version bump. The fix will be in v0.99.10!

**Comment by lpantano** [comment]
wow, nice detective work! thanks for finding this and fixing it!

**Pull request closed without merging**
